language: java
sudo: required
os:
  - linux
jdk:
  - oraclejdk8
script:
- gradle assemble
install:
- /bin/true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
notifications:
  email:
    - 877040127@qq.com
    - 1655172161@qq.com
    - 1519035296@qq.com
    - 2608659188@qq.com
    - 1072841098@qq.com
    - 2984373391@qq.com
